### ISSUE TITLE
Add project: Login to Github WITHOUT https?!

### ISSUE THREAD

**Issue by ludberg** [Qlik-PE/branch-resource-library#155]
On the page: http://branch.qlik.com/#/project/new/edit

You want us to login to github via your site depite your site not even using https. This is very sloppy and outright wrong. 

Furthermore, if you want to integrate with Github properly you need (not "can", you "need") to use their OAuth API: https://developer.github.com/v3/oauth/

Until OAuth is fixed or at least https has been enabled there is no way I would give you my github password.

**Comment by websy85** [comment]
Added the ability to link your Branch user to GitHub to provide a new "Login with Github" option that leverages the oauth api
